controller_list:
  - name: fake_right_arm_controller
    joints:
      - r_shoulder_pitch
      - r_shoulder_roll
      - r_shoulder_yaw
      - r_elbow
      - r_wrist_prosup
      - r_wrist_pitch
      - r_wrist_yaw
  - name: fake_left_arm_controller
    joints:
      - l_shoulder_pitch
      - l_shoulder_roll
      - l_shoulder_yaw
      - l_elbow
      - l_wrist_prosup
      - l_wrist_pitch
      - l_wrist_yaw
  - name: fake_right_arm_torso_controller
    joints:
      - torso_pitch
      - torso_roll
      - torso_yaw
      - r_shoulder_pitch
      - r_shoulder_roll
      - r_shoulder_yaw
      - r_elbow
      - r_wrist_prosup
      - r_wrist_pitch
      - r_wrist_yaw
  - name: fake_left_arm_torso_controller
    joints:
      - torso_pitch
      - torso_roll
      - torso_yaw
      - l_shoulder_pitch
      - l_shoulder_roll
      - l_shoulder_yaw
      - l_elbow
      - l_wrist_prosup
      - l_wrist_pitch
      - l_wrist_yaw
  - name: fake_both_arms_controller
    joints:
      - l_shoulder_pitch
      - l_shoulder_roll
      - l_shoulder_yaw
      - l_elbow
      - l_wrist_prosup
      - l_wrist_pitch
      - l_wrist_yaw
      - r_shoulder_pitch
      - r_shoulder_roll
      - r_shoulder_yaw
      - r_elbow
      - r_wrist_prosup
      - r_wrist_pitch
      - r_wrist_yaw
  - name: fake_both_arms_torso_controller
    joints:
      - torso_pitch
      - torso_roll
      - torso_yaw
      - l_shoulder_pitch
      - l_shoulder_roll
      - l_shoulder_yaw
      - l_elbow
      - l_wrist_prosup
      - l_wrist_pitch
      - l_wrist_yaw
      - r_shoulder_pitch
      - r_shoulder_roll
      - r_shoulder_yaw
      - r_elbow
      - r_wrist_prosup
      - r_wrist_pitch
      - r_wrist_yaw