# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  l_elbow:
    has_velocity_limits: true
    max_velocity: 50000
    has_acceleration_limits: false
    max_acceleration: 0
  l_shoulder_pitch:
    has_velocity_limits: true
    max_velocity: 50000
    has_acceleration_limits: false
    max_acceleration: 0
  l_shoulder_roll:
    has_velocity_limits: true
    max_velocity: 50000
    has_acceleration_limits: false
    max_acceleration: 0
  l_shoulder_yaw:
    has_velocity_limits: true
    max_velocity: 50000
    has_acceleration_limits: false
    max_acceleration: 0
  l_wrist_pitch:
    has_velocity_limits: true
    max_velocity: 50000
    has_acceleration_limits: false
    max_acceleration: 0
  l_wrist_prosup:
    has_velocity_limits: true
    max_velocity: 50000
    has_acceleration_limits: false
    max_acceleration: 0
  l_wrist_yaw:
    has_velocity_limits: true
    max_velocity: 50000
    has_acceleration_limits: false
    max_acceleration: 0
  r_elbow:
    has_velocity_limits: true
    max_velocity: 50000
    has_acceleration_limits: false
    max_acceleration: 0
  r_shoulder_pitch:
    has_velocity_limits: true
    max_velocity: 50000
    has_acceleration_limits: false
    max_acceleration: 0
  r_shoulder_roll:
    has_velocity_limits: true
    max_velocity: 50000
    has_acceleration_limits: false
    max_acceleration: 0
  r_shoulder_yaw:
    has_velocity_limits: true
    max_velocity: 50000
    has_acceleration_limits: false
    max_acceleration: 0
  r_wrist_pitch:
    has_velocity_limits: true
    max_velocity: 50000
    has_acceleration_limits: false
    max_acceleration: 0
  r_wrist_prosup:
    has_velocity_limits: true
    max_velocity: 50000
    has_acceleration_limits: false
    max_acceleration: 0
  r_wrist_yaw:
    has_velocity_limits: true
    max_velocity: 50000
    has_acceleration_limits: false
    max_acceleration: 0
  torso_pitch:
    has_velocity_limits: true
    max_velocity: 50000
    has_acceleration_limits: false
    max_acceleration: 0
  torso_roll:
    has_velocity_limits: true
    max_velocity: 50000
    has_acceleration_limits: false
    max_acceleration: 0
  torso_yaw:
    has_velocity_limits: true
    max_velocity: 50000
    has_acceleration_limits: false
    max_acceleration: 0